//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimateSniper_SchedulerEngine {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class SchedulerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SchedulerSettings defaultInstance = ((SchedulerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SchedulerSettings())));
        
        public static SchedulerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int Frequency_Snipe_LoadEndingSnipes {
            get {
                return ((int)(this["Frequency_Snipe_LoadEndingSnipes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int Frequency_Snipe_CheckSnipeValidity {
            get {
                return ((int)(this["Frequency_Snipe_CheckSnipeValidity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Frequency_Snipe_CheckTime {
            get {
                return ((int)(this["Frequency_Snipe_CheckTime"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Frequency_BidOptimizer_RefreshSnipes {
            get {
                return ((int)(this["Frequency_BidOptimizer_RefreshSnipes"]));
            }
        }
    }
}
