//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimateSniper_Services {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class ServicesSettingsProduction : global::System.Configuration.ApplicationSettingsBase {
        
        private static ServicesSettingsProduction defaultInstance = ((ServicesSettingsProduction)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ServicesSettingsProduction())));
        
        public static ServicesSettingsProduction Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.ebay.com/wsapi")]
        public string eBayUrl {
            get {
                return ((string)(this["eBayUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("667")]
        public string eBayVersion {
            get {
                return ((string)(this["eBayVersion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.10.2.155")]
        public string EndUserIP {
            get {
                return ((string)(this["EndUserIP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://signin.ebay.com/ws/eBayISAPI.dll?SignIn&RuName={0}&SessID={1}")]
        public string SignInURL {
            get {
                return ((string)(this["SignInURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Camille_Valley-CamilleV-0118-4-nbmuievuz")]
        public string RUName {
            get {
                return ((string)(this["RUName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://svcs.ebay.com/services/search/FindingService/v1")]
        public string eBayFindingUrl {
            get {
                return ((string)(this["eBayFindingUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int nbAPIRetry {
            get {
                return ((int)(this["nbAPIRetry"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mail.snipeagent.com")]
        public string SMTPAddress {
            get {
                return ((string)(this["SMTPAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"AgAAAA**AQAAAA**aAAAAA**8gABTA**nY+sHZ2PrBmdj6wVnY+sEZ2PrA2dj6wJmIulDJGLqAWdj6x9nY+seQ**ytMAAA**AAMAAA**0dqu2CDl9jng9LJ2zSL2n7E1Z/Rx62bFOtunVNXRgxn07jnq5ZbztiepB0iZVqz+k5MDPRi17Zskx906GBWo99dN2DKOGuU/enaeBfznkdlYbcp9GYYT8TqTPF+zaFj/iBJsTjgR4V75/B2fYA/BHEDaOqbWUKCgqW8UJx+RE98jXmb9+e3sz6/XWmvgZ6USE6pwoxzdDE4rxrziYfoURTEqYp2Xacbb9W9SC2qIg6qhm8dWdkYSsCoAUcf1c0bXf1oinTj+T6SHaYvrGLGPA6evIbTp+K0jf7IFCHH4npfbXxDwz96hV44JfqZiLvVApWOCv+T+/DyE1/DbxyOdtgmbGsvxNUlOYKh3YoSicSpDcAwkWqVCh8ckjNINdGwU9SEilHG7Cgez86NgjGvGcc3qXfbcY01AEVrmXegzFUcm7KHcBaZYe9GvaEuHHRez6GwwoPKekdCEZQe1etbDs2YAEVp6u7vjhXT9AFa45icA6hUxf3+f4IQ5Y8sEATi1ia7t9fo+Mr71GZUoD6S6sBlumKuX0XfkEfOoZrrupbxziFfPMntRT3xWY5lb2MZy01vEaJdkPhCH9+qpaewg356+PeHc6C9CC6dRYXQIeEy15eNalpbnaQmMnm0DBGc7U+J5DGXUAUO6csDcRM3rdx9Koe0uBI+DaOi/NP437AQu2yN7DB8EhNPGXQshW8lBCVWrcETrnad0QqrRoiMXUY+ukgwFxpPB68kBNBU3quAt7QDSuRLbL6FTIvoT8YnN")]
        public string DefaultGeteBayTimeToken {
            get {
                return ((string)(this["DefaultGeteBayTimeToken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11/20/2011 11:56:34")]
        public global::System.DateTime DefaultGeteBayTimeTokenExpirationDate {
            get {
                return ((global::System.DateTime)(this["DefaultGeteBayTimeTokenExpirationDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" https://www.paypal.com/cgi-bin/webscr")]
        public string PayPalGateway {
            get {
                return ((string)(this["PayPalGateway"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://open.api.ebay.com/shopping")]
        public string ShoppingServerUrl {
            get {
                return ((string)(this["ShoppingServerUrl"]));
            }
        }
    }
}
