//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimateSniper_Services {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class ServicesSettingsSandbox : global::System.Configuration.ApplicationSettingsBase {
        
        private static ServicesSettingsSandbox defaultInstance = ((ServicesSettingsSandbox)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ServicesSettingsSandbox())));
        
        public static ServicesSettingsSandbox Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2d27d104-88ef-47e1-b156-f68ddc07ff4d")]
        public string eBayDevID {
            get {
                return ((string)(this["eBayDevID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CamilleV-0118-4b78-9067-c02e03d2bd15")]
        public string eBayAppID {
            get {
                return ((string)(this["eBayAppID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("790b9030-13e6-4311-a8fb-255006586a3f")]
        public string eBayCertID {
            get {
                return ((string)(this["eBayCertID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.sandbox.ebay.com/wsapi")]
        public string eBayUrl {
            get {
                return ((string)(this["eBayUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("661")]
        public string eBayVersion {
            get {
                return ((string)(this["eBayVersion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.10.2.155")]
        public string EndUserIP {
            get {
                return ((string)(this["EndUserIP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://signin.sandbox.ebay.com/ws/eBayISAPI.dll?SignIn&RuName={0}&SessID={1}")]
        public string SignInURL {
            get {
                return ((string)(this["SignInURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Camille_Valley-CamilleV-0118-4-hfraj")]
        public string RUName {
            get {
                return ((string)(this["RUName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://svcs.ebay.com/services/search/FindingService/v1")]
        public string eBayFindingUrl {
            get {
                return ((string)(this["eBayFindingUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int nbAPIRetry {
            get {
                return ((int)(this["nbAPIRetry"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mail.snipeagent.com")]
        public string SMTPAddress {
            get {
                return ((string)(this["SMTPAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"AgAAAA**AQAAAA**aAAAAA**QQQ5Tw**nY+sHZ2PrBmdj6wVnY+sEZ2PrA2dj6wFk4GhCJSKpQmdj6x9nY+seQ**UUsBAA**AAMAAA**gMSCJsIvF1prIO+hMSHfB/kHBmYW75Mi5sJ2w1YgzbcwNFyutGzbf96ubTDTYXjKlTYj8FwzJKS0Zm84ipbSB8sNhdcPTMO5qzHo0d/XJG9XeDSD4I2Q/wOydCTBXTfvlvIeEOlgpjctYbVHfDEAdQ8ibs11Kjwsr77U5gy5b56h0qhXwXUjQ15rx3LsUd6f0J4TECOXfKG1BedoJvHhIeLCMx9HB9VyBSCTWVtkXaJZVsDuy6l5/IBuzjubqcv9tb/8E5aqVKvRHDnotbJlFmzi3ml9utPvRjVPsCec3uc1/qNB02ZMeYCOUNORq+x7t3T74XD+401QvxFYQYW6DZSCOy/7XbTZOtHEXZtEE1nCfWKid92KryqewGNyOji/P0T9TCL+X/vzJE9+x22vO856tBhguonssbGiwYoZAAHvpfNpe/7ni9KdboA6+V5xlVldI3Dz5sSm5Gcr+jE7nAPwu3ZwZTPd0eAemKRT6pF+5t7cbVHzMUrBc/NqG1ENm3p5SSCurgpGLX0cifOJp057NBijz1OlIfJRRvnnDY92oICzp2mLIBvD4yLy+aaKrr1fPFYHeapl3/eQzocnfsOB60gddR+QLYpmuIw78O6c9Tlu3+A0EvJTc0ctmPmRn5orkEORlPFL1ocdffArm20Wj1wMweT0Iit1Ca3n5iRaoJsZfEZFfKin9F6fv7JRqiUejY4pkwU2Ak57DMcqMzVDU9QuYgtgOiW+urUpA8N3PgulR6L3u375wD2D/tYt")]
        public string DefaultGeteBayTimeToken {
            get {
                return ((string)(this["DefaultGeteBayTimeToken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("08/06/2013 12:38:00")]
        public global::System.DateTime DefaultGeteBayTimeTokenExpirationDate {
            get {
                return ((global::System.DateTime)(this["DefaultGeteBayTimeTokenExpirationDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" https://www.sandbox.paypal.com/cgi-bin/webscr")]
        public string PayPalGateway {
            get {
                return ((string)(this["PayPalGateway"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://open.api.sandbox.ebay.com/shopping")]
        public string ShoppingServerUrl {
            get {
                return ((string)(this["ShoppingServerUrl"]));
            }
        }
    }
}
