//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.lang", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send question.
        /// </summary>
        internal static string AboutUs_btnSendEmail {
            get {
                return ResourceManager.GetString("AboutUs_btnSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can reach us by sumitting this form:.
        /// </summary>
        internal static string AboutUs_Contact {
            get {
                return ResourceManager.GetString("AboutUs_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message:.
        /// </summary>
        internal static string AboutUs_EmailBody {
            get {
                return ResourceManager.GetString("AboutUs_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject:.
        /// </summary>
        internal static string AboutUs_EmailTitle {
            get {
                return ResourceManager.GetString("AboutUs_EmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As ex eBay employees, we know from inside how eBay systems work and could develop the perfect snipe solution. &lt;br /&gt;&lt;br /&gt;
        ///If you are happy with our services, You can contribute directly through a PayPal donation. PayPal is a way for you to send and receive money via e-mail.&lt;br /&gt; &lt;br /&gt;
        ///Donating would help us pay our server bills and keep the service free.
        ///&lt;br /&gt;&lt;br /&gt;.
        /// </summary>
        internal static string AboutUs_Info {
            get {
                return ResourceManager.GetString("AboutUs_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string AboutUs_Title {
            get {
                return ResourceManager.GetString("AboutUs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email:.
        /// </summary>
        internal static string AboutUs_UserEmailAddress {
            get {
                return ResourceManager.GetString("AboutUs_UserEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Snipe Agent allows you to organise your snipes in groups. Most of the time a group will contain similar items from different sellers. As soon as you win one auction at the price you want, we&apos;ll automatically cancel the rest of your bids, for the selected group.&lt;/p&gt;&lt;p&gt;From this page, you can manage your groups.&lt;/p&gt;.
        /// </summary>
        internal static string Categories_Explainations {
            get {
                return ResourceManager.GetString("Categories_Explainations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage my groups.
        /// </summary>
        internal static string Categories_Title {
            get {
                return ResourceManager.GetString("Categories_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert messages:.
        /// </summary>
        internal static string Features_Alert {
            get {
                return ResourceManager.GetString("Features_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 24h, your snipe will be checked. If you have been overbidded, you will receive an email..
        /// </summary>
        internal static string Features_AlertExp {
            get {
                return ResourceManager.GetString("Features_AlertExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto retry:.
        /// </summary>
        internal static string Features_AutoRetry {
            get {
                return ResourceManager.GetString("Features_AutoRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Often, professional sellers propose several time the same item. 
        ///        If you lose an auction, we will look automatically if a similar item is available and will create a snipe.
        ///        You have the possibility to increase your bid between each try to maximize your chance of winning..
        /// </summary>
        internal static string Features_AutoRetryExp {
            get {
                return ResourceManager.GetString("Features_AutoRetryExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string Features_Free {
            get {
                return ResourceManager.GetString("Features_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group sniping:.
        /// </summary>
        internal static string Features_Group {
            get {
                return ResourceManager.GetString("Features_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature allows you to bid on the same item from different sellers. 
        ///            As soon as you win one auction at the price you want, we&apos;ll automatically cancel the rest of your bids..
        /// </summary>
        internal static string Features_GroupExp {
            get {
                return ResourceManager.GetString("Features_GroupExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile website m.snipeagent.com:.
        /// </summary>
        internal static string Features_Mobile {
            get {
                return ResourceManager.GetString("Features_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the mobile website to create or modify snipes.
        ///        This is the perfect complement to the alert system!.
        /// </summary>
        internal static string Features_MobileExp {
            get {
                return ResourceManager.GetString("Features_MobileExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Pack.
        /// </summary>
        internal static string Features_OptionPack {
            get {
                return ResourceManager.GetString("Features_OptionPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security:.
        /// </summary>
        internal static string Features_Security {
            get {
                return ResourceManager.GetString("Features_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlike most of the other snipe tools, we will never ask for your eBay credentials. 
        ///    We follow instead the official authorization process provided by eBay.
        ///    Why that?&lt;br /&gt;
        ///    - For security reasons and as required by eBay, you should never share your credentials with anyone.&lt;br /&gt;
        ///    - Moreover, you can modify your credentials on eBay with no risk for your snipes.
        /// </summary>
        internal static string Features_SecurityExp {
            get {
                return ResourceManager.GetString("Features_SecurityExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snipe system:.
        /// </summary>
        internal static string Features_SnipeSystem {
            get {
                return ResourceManager.GetString("Features_SnipeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create as many snipes as you want using our sleack and user friendly website.
        ///            You have the possibility to modify them until the last seconds of the auction..
        /// </summary>
        internal static string Features_SnipeSystemExp {
            get {
                return ResourceManager.GetString("Features_SnipeSystemExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        internal static string Features_Title {
            get {
                return ResourceManager.GetString("Features_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular update:.
        /// </summary>
        internal static string Features_Update {
            get {
                return ResourceManager.GetString("Features_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In its last day, the auction is checked every 10 minutes.
        ///        If you have been outbidded, you will receive instantly an email..
        /// </summary>
        internal static string Features_UpdateExp {
            get {
                return ResourceManager.GetString("Features_UpdateExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string ForgotPassword_btnSendPassword {
            get {
                return ResourceManager.GetString("ForgotPassword_btnSendPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your email or your user name:.
        /// </summary>
        internal static string ForgotPassword_EmailOrName {
            get {
                return ResourceManager.GetString("ForgotPassword_EmailOrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To obtain your password, please enter your e-mail address and it will be emailed to you..
        /// </summary>
        internal static string ForgotPassword_Explaination {
            get {
                return ResourceManager.GetString("ForgotPassword_Explaination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive your password by email.
        /// </summary>
        internal static string ForgotPassword_Title {
            get {
                return ResourceManager.GetString("ForgotPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Alert mechanism:&lt;/p&gt; 
        ///The current auction price is above your snipe bid? You will receive an alert by email giving you a chance to revise your bid and avoid future disappointment..
        /// </summary>
        internal static string Home_Alert {
            get {
                return ResourceManager.GetString("Home_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In whatever.
        /// </summary>
        internal static string Home_explainations {
            get {
                return ResourceManager.GetString("Home_explainations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snipe Agent is a system allowing you manage online your auction in a more efficient way..
        /// </summary>
        internal static string Home_Explanations {
            get {
                return ResourceManager.GetString("Home_Explanations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our sniping service is free. Create your account in a couple of seconds and enjoy winning auctions at the best possible price..
        /// </summary>
        internal static string Home_Free {
            get {
                return ResourceManager.GetString("Home_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren’t at home but you have a new auction to snipe or received on your mobile an overbid alert and want to modify your snipe (m.snipeagent.com).
        ///Use Snipe Agent mobile features and win your auctions where ever you are..
        /// </summary>
        internal static string Home_Mobility {
            get {
                return ResourceManager.GetString("Home_Mobility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlike most of the other snipe tools, we will never ask for your eBay credentials. &lt;br/&gt;
        ///We follow instead the official authorization process provided by eBay.&lt;br/&gt;.
        /// </summary>
        internal static string Home_Security {
            get {
                return ResourceManager.GetString("Home_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snipe Agent, your eBay partner.
        /// </summary>
        internal static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All snipes.
        /// </summary>
        internal static string SnipeManagement_All {
            get {
                return ResourceManager.GetString("SnipeManagement_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cancel or modify your snipes until the last second, except the delay..
        /// </summary>
        internal static string SnipeManagement_Details {
            get {
                return ResourceManager.GetString("SnipeManagement_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Snipe Agent, you have the power to effectively manage your snipes until the last few seconds of an auction..
        /// </summary>
        internal static string SnipeManagement_Explainations {
            get {
                return ResourceManager.GetString("SnipeManagement_Explainations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which snipes to display:.
        /// </summary>
        internal static string SnipeManagement_ListTypeSelection {
            get {
                return ResourceManager.GetString("SnipeManagement_ListTypeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No snipe to be displayed!.
        /// </summary>
        internal static string SnipeManagement_NoSnipe {
            get {
                return ResourceManager.GetString("SnipeManagement_NoSnipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open snipes.
        /// </summary>
        internal static string SnipeManagement_Open {
            get {
                return ResourceManager.GetString("SnipeManagement_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only recent.
        /// </summary>
        internal static string SnipeManagement_Recent {
            get {
                return ResourceManager.GetString("SnipeManagement_Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage my snipes.
        /// </summary>
        internal static string SnipeManagement_Title {
            get {
                return ResourceManager.GetString("SnipeManagement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Won snipes.
        /// </summary>
        internal static string SnipeManagement_Won {
            get {
                return ResourceManager.GetString("SnipeManagement_Won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        internal static string UCCategoryManagement_btnAddNew {
            get {
                return ResourceManager.GetString("UCCategoryManagement_btnAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string UCCategoryManagement_btnCancel {
            get {
                return ResourceManager.GetString("UCCategoryManagement_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string UCCategoryManagement_btnDelete {
            get {
                return ResourceManager.GetString("UCCategoryManagement_btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UCCategoryManagement_btnUpdate {
            get {
                return ResourceManager.GetString("UCCategoryManagement_btnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel your changes?.
        /// </summary>
        internal static string UCCategoryManagement_ConfirmCancel {
            get {
                return ResourceManager.GetString("UCCategoryManagement_ConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this category?.
        /// </summary>
        internal static string UCCategoryManagement_ConfirmDelete {
            get {
                return ResourceManager.GetString("UCCategoryManagement_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string UCCategoryManagement_txtBxName {
            get {
                return ResourceManager.GetString("UCCategoryManagement_txtBxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string UCMenu_AboutUs {
            get {
                return ResourceManager.GetString("UCMenu_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        internal static string UCMenu_Features {
            get {
                return ResourceManager.GetString("UCMenu_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        internal static string UCMenu_ForgotPassword {
            get {
                return ResourceManager.GetString("UCMenu_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string UCMenu_Home {
            get {
                return ResourceManager.GetString("UCMenu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string UCMenu_LogIn {
            get {
                return ResourceManager.GetString("UCMenu_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string UCMenu_LogOut {
            get {
                return ResourceManager.GetString("UCMenu_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobility.
        /// </summary>
        internal static string UCMenu_Mobility {
            get {
                return ResourceManager.GetString("UCMenu_Mobility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My groups.
        /// </summary>
        internal static string UCMenu_MyCategories {
            get {
                return ResourceManager.GetString("UCMenu_MyCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My information.
        /// </summary>
        internal static string UCMenu_MyInfo {
            get {
                return ResourceManager.GetString("UCMenu_MyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My snipes.
        /// </summary>
        internal static string UCMenu_MySnipes {
            get {
                return ResourceManager.GetString("UCMenu_MySnipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login:.
        /// </summary>
        internal static string UCMenu_Name {
            get {
                return ResourceManager.GetString("UCMenu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string UCMenu_Password {
            get {
                return ResourceManager.GetString("UCMenu_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string UCMenu_Register {
            get {
                return ResourceManager.GetString("UCMenu_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why.
        /// </summary>
        internal static string UCMenu_WhatsSnipe {
            get {
                return ResourceManager.GetString("UCMenu_WhatsSnipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Often, professional sellers propose several time the same item. If you lose an auction, we will look automatically if a similar item is available and will create a snipe. You have the possibility to increase your bid between each try to maximize your chance of winning. You need to have the Option Pack to use this option..
        /// </summary>
        internal static string UCSnipeDetails_AutoRetryHelp {
            get {
                return ResourceManager.GetString("UCSnipeDetails_AutoRetryHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string UCSnipeDetails_btnCancel {
            get {
                return ResourceManager.GetString("UCSnipeDetails_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string UCSnipeDetails_btnDisable {
            get {
                return ResourceManager.GetString("UCSnipeDetails_btnDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string UCSnipeDetails_btnSave {
            get {
                return ResourceManager.GetString("UCSnipeDetails_btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto retry with similar item:.
        /// </summary>
        internal static string UCSnipeDetails_ckbx_AutoSnipe {
            get {
                return ResourceManager.GetString("UCSnipeDetails_ckbx_AutoSnipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click n&apos; Bid:.
        /// </summary>
        internal static string UCSnipeDetails_ClickNBid {
            get {
                return ResourceManager.GetString("UCSnipeDetails_ClickNBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel your changes?.
        /// </summary>
        internal static string UCSnipeDetails_ConfirmCancel {
            get {
                return ResourceManager.GetString("UCSnipeDetails_ConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to snipe this item?.
        /// </summary>
        internal static string UCSnipeDetails_ConfirmCreation {
            get {
                return ResourceManager.GetString("UCSnipeDetails_ConfirmCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel this snipe?.
        /// </summary>
        internal static string UCSnipeDetails_ConfirmDelete {
            get {
                return ResourceManager.GetString("UCSnipeDetails_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save the changes you made?.
        /// </summary>
        internal static string UCSnipeDetails_ConfirmSave {
            get {
                return ResourceManager.GetString("UCSnipeDetails_ConfirmSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bid will be converted to the item currency, if they are different..
        /// </summary>
        internal static string UCSnipeDetails_CurrencyHelp {
            get {
                return ResourceManager.GetString("UCSnipeDetails_CurrencyHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string UCSnipeDetails_DefaultText {
            get {
                return ResourceManager.GetString("UCSnipeDetails_DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To respect eBay policies, your bid will be placed randomly in the last 15 seconds of the bid..
        /// </summary>
        internal static string UCSnipeDetails_DelayHelp {
            get {
                return ResourceManager.GetString("UCSnipeDetails_DelayHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase:.
        /// </summary>
        internal static string UCSnipeDetails_Increase {
            get {
                return ResourceManager.GetString("UCSnipeDetails_Increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item current price:.
        /// </summary>
        internal static string UCSnipeDetails_ItemCurrentPrice {
            get {
                return ResourceManager.GetString("UCSnipeDetails_ItemCurrentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item end date:.
        /// </summary>
        internal static string UCSnipeDetails_ItemEndDate {
            get {
                return ResourceManager.GetString("UCSnipeDetails_ItemEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Id:.
        /// </summary>
        internal static string UCSnipeDetails_ItemID {
            get {
                return ResourceManager.GetString("UCSnipeDetails_ItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller ID:.
        /// </summary>
        internal static string UCSnipeDetails_ItemSellerID {
            get {
                return ResourceManager.GetString("UCSnipeDetails_ItemSellerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of auto retry:.
        /// </summary>
        internal static string UCSnipeDetails_NbRetry {
            get {
                return ResourceManager.GetString("UCSnipeDetails_NbRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your maximum bid:.
        /// </summary>
        internal static string UCSnipeDetails_SnipeBid {
            get {
                return ResourceManager.GetString("UCSnipeDetails_SnipeBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories:.
        /// </summary>
        internal static string UCSnipeDetails_SnipeCategories {
            get {
                return ResourceManager.GetString("UCSnipeDetails_SnipeCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay in seconds:.
        /// </summary>
        internal static string UCSnipeDetails_SnipeDelay {
            get {
                return ResourceManager.GetString("UCSnipeDetails_SnipeDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random btw 5 and 15 secs.
        /// </summary>
        internal static string UCSnipeDetails_SnipeDelayInfo {
            get {
                return ResourceManager.GetString("UCSnipeDetails_SnipeDelayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of the snipe:.
        /// </summary>
        internal static string UCSnipeDetails_SnipeDescription {
            get {
                return ResourceManager.GetString("UCSnipeDetails_SnipeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the snipe:.
        /// </summary>
        internal static string UCSnipeDetails_SnipeName {
            get {
                return ResourceManager.GetString("UCSnipeDetails_SnipeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string UCSnipeDetails_SnipeStatus {
            get {
                return ResourceManager.GetString("UCSnipeDetails_SnipeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniping style:.
        /// </summary>
        internal static string UCSnipeDetails_SnipeStyle {
            get {
                return ResourceManager.GetString("UCSnipeDetails_SnipeStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid optimizer.
        /// </summary>
        internal static string UCSnipeDetails_SnipeStyleBidOptimizer {
            get {
                return ResourceManager.GetString("UCSnipeDetails_SnipeStyleBidOptimizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        internal static string UCSnipeDetails_SnipeStyleClassic {
            get {
                return ResourceManager.GetString("UCSnipeDetails_SnipeStyleClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string UCSnipeDetails_SnipeStyleManual {
            get {
                return ResourceManager.GetString("UCSnipeDetails_SnipeStyleManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string UCSnipeIt_btnGetInfo {
            get {
                return ResourceManager.GetString("UCSnipeIt_btnGetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item last known price:.
        /// </summary>
        internal static string UCSnipeIt_ItemCurrentPrice {
            get {
                return ResourceManager.GetString("UCSnipeIt_ItemCurrentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item id or URL to snipe:.
        /// </summary>
        internal static string UCSnipeIt_ItemID {
            get {
                return ResourceManager.GetString("UCSnipeIt_ItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item title:.
        /// </summary>
        internal static string UCSnipeIt_ItemTitle {
            get {
                return ResourceManager.GetString("UCSnipeIt_ItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new snipe:.
        /// </summary>
        internal static string UCSnipeIt_NewSnipe {
            get {
                return ResourceManager.GetString("UCSnipeIt_NewSnipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        internal static string UserDetails_AccountAssociated {
            get {
                return ResourceManager.GetString("UserDetails_AccountAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string UserDetails_AccountNotAssociated {
            get {
                return ResourceManager.GetString("UserDetails_AccountNotAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive alerts when your snipes are overbidded.
        /// </summary>
        internal static string UserDetails_Alerts {
            get {
                return ResourceManager.GetString("UserDetails_Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string UserDetails_btnDisable {
            get {
                return ResourceManager.GetString("UserDetails_btnDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in eBay.
        /// </summary>
        internal static string UserDetails_btnRedirect {
            get {
                return ResourceManager.GetString("UserDetails_btnRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string UserDetails_btnSave {
            get {
                return ResourceManager.GetString("UserDetails_btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish sign in.
        /// </summary>
        internal static string UserDetails_btnUpdate {
            get {
                return ResourceManager.GetString("UserDetails_btnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organise your snipe into categories. Successful snipes will cancel the snipes from the same categories..
        /// </summary>
        internal static string UserDetails_Categories {
            get {
                return ResourceManager.GetString("UserDetails_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to disable permanently your account?.
        /// </summary>
        internal static string UserDetails_ConfirmDisable {
            get {
                return ResourceManager.GetString("UserDetails_ConfirmDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;Help us keep the service free:.
        /// </summary>
        internal static string UserDetails_Donation {
            get {
                return ResourceManager.GetString("UserDetails_Donation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Extend your Option Pack for 6 months. Its only 10$!&lt;/p&gt;.
        /// </summary>
        internal static string UserDetails_ExtendOptions {
            get {
                return ResourceManager.GetString("UserDetails_ExtendOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EBay account associated:.
        /// </summary>
        internal static string UserDetails_GetToken {
            get {
                return ResourceManager.GetString("UserDetails_GetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Snipe Agent on your mobile and manage your snipes where ever you are: m.snipeagent.com.
        /// </summary>
        internal static string UserDetails_Mobile {
            get {
                return ResourceManager.GetString("UserDetails_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;To welcome you, get the Option Pack for free for 2 months:&lt;/p&gt;.
        /// </summary>
        internal static string UserDetails_OptionsExplaination {
            get {
                return ResourceManager.GetString("UserDetails_OptionsExplaination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to assign your eBay account.
        /// </summary>
        internal static string UserDetails_RedirectHelpHelp {
            get {
                return ResourceManager.GetString("UserDetails_RedirectHelpHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Thanks for registering.&lt;/p&gt;
        ///&lt;p&gt;You will now be redirected to eBay sign in. Please click on the button &quot;Assing my eBay account&quot;&lt;/p&gt;.
        /// </summary>
        internal static string UserDetails_RegistrationConfirmation {
            get {
                return ResourceManager.GetString("UserDetails_RegistrationConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  This is the site we will use to interact with eBay. This will condition the language of the emails sent to you by eBay..
        /// </summary>
        internal static string UserDetails_SiteIDHelp {
            get {
                return ResourceManager.GetString("UserDetails_SiteIDHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us and receive support in the best delay.
        /// </summary>
        internal static string UserDetails_Support {
            get {
                return ResourceManager.GetString("UserDetails_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your information / Create an account.
        /// </summary>
        internal static string UserDetails_Title {
            get {
                return ResourceManager.GetString("UserDetails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;Your eBay account is associated till:.
        /// </summary>
        internal static string UserDetails_TokenExpirationDate {
            get {
                return ResourceManager.GetString("UserDetails_TokenExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here once you signed in eBay.
        /// </summary>
        internal static string UserDetails_UpdateHelpHelp {
            get {
                return ResourceManager.GetString("UserDetails_UpdateHelpHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User active since:.
        /// </summary>
        internal static string UserDetails_UserActivityDate {
            get {
                return ResourceManager.GetString("UserDetails_UserActivityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency:.
        /// </summary>
        internal static string UserDetails_UserCurrency {
            get {
                return ResourceManager.GetString("UserDetails_UserCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ebay User ID.
        /// </summary>
        internal static string UserDetails_UserEbayUserID {
            get {
                return ResourceManager.GetString("UserDetails_UserEbayUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ebay User password.
        /// </summary>
        internal static string UserDetails_UserEbayUserPwd {
            get {
                return ResourceManager.GetString("UserDetails_UserEbayUserPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string UserDetails_UserEmail {
            get {
                return ResourceManager.GetString("UserDetails_UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        internal static string UserDetails_UserName {
            get {
                return ResourceManager.GetString("UserDetails_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Option Pack is valid till:.
        /// </summary>
        internal static string UserDetails_UserOptionPackEndDate {
            get {
                return ResourceManager.GetString("UserDetails_UserOptionPackEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string UserDetails_UserPassword {
            get {
                return ResourceManager.GetString("UserDetails_UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site registration:.
        /// </summary>
        internal static string UserDetails_UserSiteID {
            get {
                return ResourceManager.GetString("UserDetails_UserSiteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto retry with similar items from the same seller..
        /// </summary>
        internal static string WhatsSnipe_AutoRetry {
            get {
                return ResourceManager.GetString("WhatsSnipe_AutoRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniping will keep you out of bidding wars.
        /// </summary>
        internal static string WhatsSnipe_BiddingWar {
            get {
                return ResourceManager.GetString("WhatsSnipe_BiddingWar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change your mind until the last seconds..
        /// </summary>
        internal static string WhatsSnipe_Change {
            get {
                return ResourceManager.GetString("WhatsSnipe_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra features:.
        /// </summary>
        internal static string WhatsSnipe_ExtraFeatures {
            get {
                return ResourceManager.GetString("WhatsSnipe_ExtraFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups bidding: bid on the same item from different sellers.
        /// </summary>
        internal static string WhatsSnipe_Group {
            get {
                return ResourceManager.GetString("WhatsSnipe_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t need to install anything on your computer!.
        /// </summary>
        internal static string WhatsSnipe_NoDL {
            get {
                return ResourceManager.GetString("WhatsSnipe_NoDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your computer doesn&apos;t have to be on to have the snipes working..
        /// </summary>
        internal static string WhatsSnipe_NoPC {
            get {
                return ResourceManager.GetString("WhatsSnipe_NoPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online service:.
        /// </summary>
        internal static string WhatsSnipe_Online {
            get {
                return ResourceManager.GetString("WhatsSnipe_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respect of eBay policies:.
        /// </summary>
        internal static string WhatsSnipe_Policies {
            get {
                return ResourceManager.GetString("WhatsSnipe_Policies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We don&apos;t ask for your eBay credentials.
        /// </summary>
        internal static string WhatsSnipe_RandomCredentials {
            get {
                return ResourceManager.GetString("WhatsSnipe_RandomCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bid will be placed randomnly in the last 15 seconds.
        /// </summary>
        internal static string WhatsSnipe_RandomDelay {
            get {
                return ResourceManager.GetString("WhatsSnipe_RandomDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniping will hide your bid price from other bidders.
        /// </summary>
        internal static string WhatsSnipe_SecretBid {
            get {
                return ResourceManager.GetString("WhatsSnipe_SecretBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snipes:.
        /// </summary>
        internal static string WhatsSnipe_Snipes {
            get {
                return ResourceManager.GetString("WhatsSnipe_Snipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why should you use our services.
        /// </summary>
        internal static string WhatsSnipe_Title {
            get {
                return ResourceManager.GetString("WhatsSnipe_Title", resourceCulture);
            }
        }
    }
}
