//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class mess {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal mess() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.mess", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action has been cancelled..
        /// </summary>
        internal static string ActionCancelled {
            get {
                return ResourceManager.GetString("ActionCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category has been created..
        /// </summary>
        internal static string CategoryCreated {
            get {
                return ResourceManager.GetString("CategoryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category has been deleted..
        /// </summary>
        internal static string CategoryDeleted {
            get {
                return ResourceManager.GetString("CategoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category ID couldn&apos;t be found..
        /// </summary>
        internal static string CategoryIDNotFound {
            get {
                return ResourceManager.GetString("CategoryIDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category ID should be null.
        /// </summary>
        internal static string CategoryIDNotNull {
            get {
                return ResourceManager.GetString("CategoryIDNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The categoryID shouldn&apos;t be null.
        /// </summary>
        internal static string CategoryIDNull {
            get {
                return ResourceManager.GetString("CategoryIDNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t have more than 10 active categories..
        /// </summary>
        internal static string CategoryMaxNumberReached {
            get {
                return ResourceManager.GetString("CategoryMaxNumberReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a name for your category.
        /// </summary>
        internal static string CategoryNameEmpty {
            get {
                return ResourceManager.GetString("CategoryNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category has been updated..
        /// </summary>
        internal static string CategoryUpdated {
            get {
                return ResourceManager.GetString("CategoryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes have been cancelled.
        /// </summary>
        internal static string ChangesCancelled {
            get {
                return ResourceManager.GetString("ChangesCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been sent.
        /// </summary>
        internal static string ForgotPasswordEmailSent {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item has already ended or the delay is too short..
        /// </summary>
        internal static string ItemEndedOrDelayToShort {
            get {
                return ResourceManager.GetString("ItemEndedOrDelayToShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid item ID..
        /// </summary>
        internal static string ItemIDNotANumber {
            get {
                return ResourceManager.GetString("ItemIDNotANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have a snipe for this item.
        /// </summary>
        internal static string SnipeAlreadyExists {
            get {
                return ResourceManager.GetString("SnipeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You bid is invalid. It should be a number superior to 0..
        /// </summary>
        internal static string SnipeBidInvalid {
            get {
                return ResourceManager.GetString("SnipeBidInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bid must be a number..
        /// </summary>
        internal static string SnipeBidNotANumber {
            get {
                return ResourceManager.GetString("SnipeBidNotANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bid was successfully placed..
        /// </summary>
        internal static string SnipeBidPlaced {
            get {
                return ResourceManager.GetString("SnipeBidPlaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bid is too low..
        /// </summary>
        internal static string SnipeBidUnderCurrentPrice {
            get {
                return ResourceManager.GetString("SnipeBidUnderCurrentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The snipe has been created..
        /// </summary>
        internal static string SnipeCreated {
            get {
                return ResourceManager.GetString("SnipeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The snipe delay is in seconds. It should be 3, 7 or 10..
        /// </summary>
        internal static string SnipeDelayInvalid {
            get {
                return ResourceManager.GetString("SnipeDelayInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The snipe has been cancelled..
        /// </summary>
        internal static string SnipeDeleted {
            get {
                return ResourceManager.GetString("SnipeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The snipe ID should be null.
        /// </summary>
        internal static string SnipeIDNotNull {
            get {
                return ResourceManager.GetString("SnipeIDNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The snipe ID shouldn&apos;t be null.
        /// </summary>
        internal static string SnipeIDNull {
            get {
                return ResourceManager.GetString("SnipeIDNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item end date is empty..
        /// </summary>
        internal static string SnipeItemEndDateEmpty {
            get {
                return ResourceManager.GetString("SnipeItemEndDateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a name for your snipe.
        /// </summary>
        internal static string SnipeNameEmpty {
            get {
                return ResourceManager.GetString("SnipeNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The snipe has been updated..
        /// </summary>
        internal static string SnipeUpdated {
            get {
                return ResourceManager.GetString("SnipeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the increase between each retry. It can be &apos;0&apos;..
        /// </summary>
        internal static string SnipeWrongGenIncreaseBid {
            get {
                return ResourceManager.GetString("SnipeWrongGenIncreaseBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify how many you want to retry with similar items, in case of failure..
        /// </summary>
        internal static string SnipeWrongGenRemainingNb {
            get {
                return ResourceManager.GetString("SnipeWrongGenRemainingNb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another snipe, that ends earlier,  exists for a same category..
        /// </summary>
        internal static string SnipeYoungerSnipeSameCategoryExists {
            get {
                return ResourceManager.GetString("SnipeYoungerSnipeSameCategoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your subscription was successfully created..
        /// </summary>
        internal static string SubscriptionAdded {
            get {
                return ResourceManager.GetString("SubscriptionAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this name is already used by another member..
        /// </summary>
        internal static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to associate an eBay account..
        /// </summary>
        internal static string UserEBayAccountNotAssociated {
            get {
                return ResourceManager.GetString("UserEBayAccountNotAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide an email address..
        /// </summary>
        internal static string UserEmailEmpty {
            get {
                return ResourceManager.GetString("UserEmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldnl&apos;t find your name or email address..
        /// </summary>
        internal static string UserEmailOrUserNameNotFound {
            get {
                return ResourceManager.GetString("UserEmailOrUserNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user id isn&apos;t empty.
        /// </summary>
        internal static string UserIDNotNull {
            get {
                return ResourceManager.GetString("UserIDNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user id shouldn&apos;t be empty.
        /// </summary>
        internal static string UserIDNull {
            get {
                return ResourceManager.GetString("UserIDNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user id trying to update the action isn&apos;t the one which is logged in!.
        /// </summary>
        internal static string UserIDsMismatching {
            get {
                return ResourceManager.GetString("UserIDsMismatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IP address is empty..
        /// </summary>
        internal static string UserIPAddressEmpty {
            get {
                return ResourceManager.GetString("UserIPAddressEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IP address has a wrong format..
        /// </summary>
        internal static string UserIPAddressWrongFormat {
            get {
                return ResourceManager.GetString("UserIPAddressWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a user name..
        /// </summary>
        internal static string UserNameEmpty {
            get {
                return ResourceManager.GetString("UserNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user name should contain at least 5 caracters.
        /// </summary>
        internal static string UserNameTooSmall {
            get {
                return ResourceManager.GetString("UserNameTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user should be logged in to take this action..
        /// </summary>
        internal static string UserNotLoggedIn {
            get {
                return ResourceManager.GetString("UserNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login and password don&apos;t match!.
        /// </summary>
        internal static string UserPasswordAndLoginNotMatching {
            get {
                return ResourceManager.GetString("UserPasswordAndLoginNotMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a password..
        /// </summary>
        internal static string UserPasswordEmpty {
            get {
                return ResourceManager.GetString("UserPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password should contain at least 5 caracters.
        /// </summary>
        internal static string UserPasswordTooSmall {
            get {
                return ResourceManager.GetString("UserPasswordTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This eBay user has already been assigned..
        /// </summary>
        internal static string UserTokenAlreadyAssociated {
            get {
                return ResourceManager.GetString("UserTokenAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You account has been saved..
        /// </summary>
        internal static string UserUpdated {
            get {
                return ResourceManager.GetString("UserUpdated", resourceCulture);
            }
        }
    }
}
