//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class mess {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal mess() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.mess", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a body for your message.
        /// </summary>
        internal static string AboutUsEmailBodyEmpty {
            get {
                return ResourceManager.GetString("AboutUsEmailBodyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message was sent. You will receive an answer shortly..
        /// </summary>
        internal static string AboutUsEmailSent {
            get {
                return ResourceManager.GetString("AboutUsEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a subject for your message.
        /// </summary>
        internal static string AboutUsEmailTitleEmpty {
            get {
                return ResourceManager.GetString("AboutUsEmailTitleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a correct email address.
        /// </summary>
        internal static string AboutUsEmailWrongFormat {
            get {
                return ResourceManager.GetString("AboutUsEmailWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action has been cancelled..
        /// </summary>
        internal static string ActionCancelled {
            get {
                return ResourceManager.GetString("ActionCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category has been created..
        /// </summary>
        internal static string CategoryCreated {
            get {
                return ResourceManager.GetString("CategoryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category has been deleted..
        /// </summary>
        internal static string CategoryDeleted {
            get {
                return ResourceManager.GetString("CategoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CategoryIDNotNull {
            get {
                return ResourceManager.GetString("CategoryIDNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CategoryIDNull {
            get {
                return ResourceManager.GetString("CategoryIDNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CategoryNameEmpty {
            get {
                return ResourceManager.GetString("CategoryNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category has been updated..
        /// </summary>
        internal static string CategoryUpdated {
            get {
                return ResourceManager.GetString("CategoryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes have been cancelled.
        /// </summary>
        internal static string ChangesCancelled {
            get {
                return ResourceManager.GetString("ChangesCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ForgotPasswordEmailSent {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item has already ended or the delay is too short..
        /// </summary>
        internal static string ItemEndedOrDelayToShort {
            get {
                return ResourceManager.GetString("ItemEndedOrDelayToShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SnipeAlreadyExists {
            get {
                return ResourceManager.GetString("SnipeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SnipeBidInvalid {
            get {
                return ResourceManager.GetString("SnipeBidInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bid must be a number..
        /// </summary>
        internal static string SnipeBidNotANumber {
            get {
                return ResourceManager.GetString("SnipeBidNotANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The snipe has been created..
        /// </summary>
        internal static string SnipeCreated {
            get {
                return ResourceManager.GetString("SnipeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SnipeDelayInvalid {
            get {
                return ResourceManager.GetString("SnipeDelayInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The snipe has been cancelled..
        /// </summary>
        internal static string SnipeDeleted {
            get {
                return ResourceManager.GetString("SnipeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SnipeIDNotNull {
            get {
                return ResourceManager.GetString("SnipeIDNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SnipeIDNull {
            get {
                return ResourceManager.GetString("SnipeIDNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SnipeItemEndDateEmpty {
            get {
                return ResourceManager.GetString("SnipeItemEndDateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SnipeNameEmpty {
            get {
                return ResourceManager.GetString("SnipeNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The snipe has been updated..
        /// </summary>
        internal static string SnipeUpdated {
            get {
                return ResourceManager.GetString("SnipeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a correct email address.
        /// </summary>
        internal static string UserEmailWrongFormat {
            get {
                return ResourceManager.GetString("UserEmailWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserEmptyEmpty {
            get {
                return ResourceManager.GetString("UserEmptyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserIDNotNull {
            get {
                return ResourceManager.GetString("UserIDNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserIDNull {
            get {
                return ResourceManager.GetString("UserIDNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserIDsMismatching {
            get {
                return ResourceManager.GetString("UserIDsMismatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserNameEmpty {
            get {
                return ResourceManager.GetString("UserNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserNotLoggedIn {
            get {
                return ResourceManager.GetString("UserNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserPasswordAndLoginNotMatching {
            get {
                return ResourceManager.GetString("UserPasswordAndLoginNotMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserPasswordEmpty {
            get {
                return ResourceManager.GetString("UserPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You account has been saved..
        /// </summary>
        internal static string UserUpdated {
            get {
                return ResourceManager.GetString("UserUpdated", resourceCulture);
            }
        }
    }
}
