//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
// 
#pragma warning disable 1591

namespace UltimateSniper_SchedulerEngine.SnipeAgentScheduler {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WService_SchedulerSoap", Namespace="http://ultimatesniper.com/")]
    public partial class WService_Scheduler : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Timer_CheckTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback Timer_UpdateEndingSnipesOperationCompleted;
        
        private System.Threading.SendOrPostCallback Timer_BidOptimizer_RefreshSnipesOperationCompleted;
        
        private System.Threading.SendOrPostCallback Timer_Snipe_CheckSnipeValidityOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WService_Scheduler() {
            this.Url = global::UltimateSniper_SchedulerEngine.Properties.Settings.Default.UltimateSniper_SchedulerEngine_SnipeAgentScheduler_WService_Scheduler;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Timer_CheckTimeCompletedEventHandler Timer_CheckTimeCompleted;
        
        /// <remarks/>
        public event Timer_UpdateEndingSnipesCompletedEventHandler Timer_UpdateEndingSnipesCompleted;
        
        /// <remarks/>
        public event Timer_BidOptimizer_RefreshSnipesCompletedEventHandler Timer_BidOptimizer_RefreshSnipesCompleted;
        
        /// <remarks/>
        public event Timer_Snipe_CheckSnipeValidityCompletedEventHandler Timer_Snipe_CheckSnipeValidityCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ultimatesniper.com/Timer_CheckTime", RequestNamespace="http://ultimatesniper.com/", ResponseNamespace="http://ultimatesniper.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Timer_CheckTime() {
            object[] results = this.Invoke("Timer_CheckTime", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Timer_CheckTimeAsync() {
            this.Timer_CheckTimeAsync(null);
        }
        
        /// <remarks/>
        public void Timer_CheckTimeAsync(object userState) {
            if ((this.Timer_CheckTimeOperationCompleted == null)) {
                this.Timer_CheckTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimer_CheckTimeOperationCompleted);
            }
            this.InvokeAsync("Timer_CheckTime", new object[0], this.Timer_CheckTimeOperationCompleted, userState);
        }
        
        private void OnTimer_CheckTimeOperationCompleted(object arg) {
            if ((this.Timer_CheckTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Timer_CheckTimeCompleted(this, new Timer_CheckTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ultimatesniper.com/Timer_UpdateEndingSnipes", RequestNamespace="http://ultimatesniper.com/", ResponseNamespace="http://ultimatesniper.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Timer_UpdateEndingSnipes(bool ActiveSnipe) {
            object[] results = this.Invoke("Timer_UpdateEndingSnipes", new object[] {
                        ActiveSnipe});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Timer_UpdateEndingSnipesAsync(bool ActiveSnipe) {
            this.Timer_UpdateEndingSnipesAsync(ActiveSnipe, null);
        }
        
        /// <remarks/>
        public void Timer_UpdateEndingSnipesAsync(bool ActiveSnipe, object userState) {
            if ((this.Timer_UpdateEndingSnipesOperationCompleted == null)) {
                this.Timer_UpdateEndingSnipesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimer_UpdateEndingSnipesOperationCompleted);
            }
            this.InvokeAsync("Timer_UpdateEndingSnipes", new object[] {
                        ActiveSnipe}, this.Timer_UpdateEndingSnipesOperationCompleted, userState);
        }
        
        private void OnTimer_UpdateEndingSnipesOperationCompleted(object arg) {
            if ((this.Timer_UpdateEndingSnipesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Timer_UpdateEndingSnipesCompleted(this, new Timer_UpdateEndingSnipesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ultimatesniper.com/Timer_BidOptimizer_RefreshSnipes", RequestNamespace="http://ultimatesniper.com/", ResponseNamespace="http://ultimatesniper.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Timer_BidOptimizer_RefreshSnipes() {
            object[] results = this.Invoke("Timer_BidOptimizer_RefreshSnipes", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Timer_BidOptimizer_RefreshSnipesAsync() {
            this.Timer_BidOptimizer_RefreshSnipesAsync(null);
        }
        
        /// <remarks/>
        public void Timer_BidOptimizer_RefreshSnipesAsync(object userState) {
            if ((this.Timer_BidOptimizer_RefreshSnipesOperationCompleted == null)) {
                this.Timer_BidOptimizer_RefreshSnipesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimer_BidOptimizer_RefreshSnipesOperationCompleted);
            }
            this.InvokeAsync("Timer_BidOptimizer_RefreshSnipes", new object[0], this.Timer_BidOptimizer_RefreshSnipesOperationCompleted, userState);
        }
        
        private void OnTimer_BidOptimizer_RefreshSnipesOperationCompleted(object arg) {
            if ((this.Timer_BidOptimizer_RefreshSnipesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Timer_BidOptimizer_RefreshSnipesCompleted(this, new Timer_BidOptimizer_RefreshSnipesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ultimatesniper.com/Timer_Snipe_CheckSnipeValidity", RequestNamespace="http://ultimatesniper.com/", ResponseNamespace="http://ultimatesniper.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Timer_Snipe_CheckSnipeValidity() {
            object[] results = this.Invoke("Timer_Snipe_CheckSnipeValidity", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Timer_Snipe_CheckSnipeValidityAsync() {
            this.Timer_Snipe_CheckSnipeValidityAsync(null);
        }
        
        /// <remarks/>
        public void Timer_Snipe_CheckSnipeValidityAsync(object userState) {
            if ((this.Timer_Snipe_CheckSnipeValidityOperationCompleted == null)) {
                this.Timer_Snipe_CheckSnipeValidityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimer_Snipe_CheckSnipeValidityOperationCompleted);
            }
            this.InvokeAsync("Timer_Snipe_CheckSnipeValidity", new object[0], this.Timer_Snipe_CheckSnipeValidityOperationCompleted, userState);
        }
        
        private void OnTimer_Snipe_CheckSnipeValidityOperationCompleted(object arg) {
            if ((this.Timer_Snipe_CheckSnipeValidityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Timer_Snipe_CheckSnipeValidityCompleted(this, new Timer_Snipe_CheckSnipeValidityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Timer_CheckTimeCompletedEventHandler(object sender, Timer_CheckTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Timer_CheckTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Timer_CheckTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Timer_UpdateEndingSnipesCompletedEventHandler(object sender, Timer_UpdateEndingSnipesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Timer_UpdateEndingSnipesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Timer_UpdateEndingSnipesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Timer_BidOptimizer_RefreshSnipesCompletedEventHandler(object sender, Timer_BidOptimizer_RefreshSnipesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Timer_BidOptimizer_RefreshSnipesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Timer_BidOptimizer_RefreshSnipesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Timer_Snipe_CheckSnipeValidityCompletedEventHandler(object sender, Timer_Snipe_CheckSnipeValidityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Timer_Snipe_CheckSnipeValidityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Timer_Snipe_CheckSnipeValidityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591